### ISSUE TITLE
Easiest way to compile on Debian?

### ISSUE THREAD

**Issue by leelx78** [pschatzmann/arduino-libsbc#1]
Hi Phil,

Sorry to bug you but maybe you have some hints on this.

I'm trying to implement a server on Debian and convert SBC packets to PCM back and forth but I'm having issues in compiling anything in this library due to dependencies. What's the most sensible way to do this without having to reinvent the wheel?

Thanks as always :D

**Comment by pschatzmann** [comment]
Maybe just to highlight there are 2 options: using a minimum of Arduino Functionality which is basically just streams and data output or more functionality using an Emulator!

Here is an example for the first option: https://github.com/pschatzmann/arduino-audio-tools/blob/main/cmake-tests/codec/container-binary/CMakeLists.txt

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/wiki/Running-an-Audio-Sketch-on-the-Desktop

I don't have an example for sbc but for other codecs: https://github.com/pschatzmann/arduino-audio-tools/tree/main/cmake-tests/codec

**Comment by leelx78** [comment]
Hi @pschatzmann thanks a lot!
